package types

// Education lending module event types
const (
	EventTypeEducationLoanApplied = "education_loan_applied"
	EventTypeEducationLoanApproved = "education_loan_approved"
	EventTypeEducationLoanRejected = "education_loan_rejected"
	EventTypeEducationLoanDisbursed = "education_loan_disbursed"
	EventTypeEducationLoanRepaid = "education_loan_repaid"
	EventTypeAcademicProgressUpdated = "academic_progress_updated"
	EventTypeEmploymentStatusUpdated = "employment_status_updated"
	EventTypeScholarshipApplied = "scholarship_applied"
	EventTypeScholarshipApproved = "scholarship_approved"
	EventTypeMoratoriumStarted = "moratorium_started"
	EventTypeRepaymentStarted = "repayment_started"

	AttributeKeyLoanID = "loan_id"
	AttributeKeyBorrower = "borrower"
	AttributeKeyStudentName = "student_name"
	AttributeKeyCoApplicant = "co_applicant"
	AttributeKeyInstitution = "institution"
	AttributeKeyInstitutionType = "institution_type"
	AttributeKeyCourse = "course"
	AttributeKeyCourseType = "course_type"
	AttributeKeyAmount = "amount"
	AttributeKeyApprovedAmount = "approved_amount"
	AttributeKeyInterestRate = "interest_rate"
	AttributeKeyDuration = "duration"
	AttributeKeyStatus = "status"
	AttributeKeyReason = "reason"
	AttributeKeyTransactionHash = "transaction_hash"
	AttributeKeySemester = "semester"
	AttributeKeyGPA = "gpa"
	AttributeKeyAttendance = "attendance"
	AttributeKeyEmploymentStatus = "employment_status"
	AttributeKeyEmployer = "employer"
	AttributeKeySalary = "salary"
	AttributeKeyScholarshipID = "scholarship_id"
	AttributeKeyScholarshipType = "scholarship_type"
	AttributeKeyAcademicScore = "academic_score"
	AttributeKeyMoratoriumEndDate = "moratorium_end_date"
	AttributeKeyRepaymentStartDate = "repayment_start_date"
	AttributeKeyEMIAmount = "emi_amount"
	AttributeKeyRemainingAmount = "remaining_amount"
	AttributeKeyCollateralRequired = "collateral_required"
	AttributeKeyInterestRevised = "interest_revised"
	AttributeKeyRepaymentUpdated = "repayment_updated"
	AttributeKeyNextDisbursementDate = "next_disbursement_date"
	AttributeKeyInterestSaved = "interest_saved"
	AttributeKeyScholarshipBonus = "scholarship_bonus"
)