{{- if .Values.faucet.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "deshchain-testnet.fullname" . }}-faucet
  labels:
    {{- include "deshchain-testnet.faucetLabels" . | nindent 4 }}
spec:
  replicas: {{ .Values.faucet.replicas }}
  selector:
    matchLabels:
      {{- include "deshchain-testnet.faucetSelectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "deshchain-testnet.faucetLabels" . | nindent 8 }}
    spec:
      {{- include "deshchain-testnet.imagePullSecrets" . | nindent 6 }}
      serviceAccountName: {{ include "deshchain-testnet.serviceAccountName" . }}
      securityContext:
        fsGroup: 1000
        runAsUser: 1000
        runAsGroup: 1000
        runAsNonRoot: true
      containers:
        - name: faucet
          image: "{{ .Values.faucet.image.registry }}/{{ .Values.faucet.image.repository }}:{{ .Values.faucet.image.tag }}"
          imagePullPolicy: {{ .Values.faucet.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: CHAIN_ID
              value: {{ .Values.deshchain.chain.id | quote }}
            - name: RPC_ENDPOINT
              value: "http://{{ include "deshchain-testnet.fullname" . }}-sentry:26657"
            - name: RATE_LIMIT
              value: {{ .Values.faucet.config.rateLimit | quote }}
            - name: RATE_LIMIT_WINDOW
              value: {{ .Values.faucet.config.rateLimitWindow | quote }}
            - name: FAUCET_MNEMONIC
              valueFrom:
                secretKeyRef:
                  name: {{ include "deshchain-testnet.faucetKeysSecretName" . }}
                  key: mnemonic
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          resources:
            {{- toYaml .Values.faucet.resources | nindent 12 }}
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            capabilities:
              drop:
                - ALL
{{- end }}