{{- if .Values.sentries.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "deshchain-testnet.fullname" . }}-sentry
  labels:
    {{- include "deshchain-testnet.sentryLabels" . | nindent 4 }}
spec:
  replicas: {{ .Values.sentries.replicas }}
  selector:
    matchLabels:
      {{- include "deshchain-testnet.sentrySelectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "deshchain-testnet.sentryLabels" . | nindent 8 }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/sentry-config.yaml") . | sha256sum }}
    spec:
      {{- include "deshchain-testnet.imagePullSecrets" . | nindent 6 }}
      serviceAccountName: {{ include "deshchain-testnet.serviceAccountName" . }}
      securityContext:
        fsGroup: 1000
        runAsUser: 1000
        runAsGroup: 1000
        runAsNonRoot: true
      initContainers:
        - name: init-sentry
          image: "{{ include "deshchain-testnet.imageRegistry" . }}/{{ include "deshchain-testnet.imageRepository" . }}:{{ include "deshchain-testnet.imageTag" . }}"
          imagePullPolicy: {{ include "deshchain-testnet.imagePullPolicy" . }}
          command:
            - /bin/sh
            - -c
            - |
              set -e
              echo "Initializing sentry node..."
              
              # Initialize node if not already done
              if [ ! -f /deshchain/.deshchaind/config/node_key.json ]; then
                echo "Creating new sentry node..."
                deshchaind init $MONIKER --chain-id $CHAIN_ID --home /deshchain/.deshchaind
              fi
              
              # Copy genesis file
              cp /genesis/genesis.json /deshchain/.deshchaind/config/genesis.json
              
              # Set permissions
              chown -R 1000:1000 /deshchain/.deshchaind
              chmod -R 755 /deshchain/.deshchaind
              
              echo "Sentry initialization complete"
          env:
            {{- include "deshchain-testnet.commonEnv" . | nindent 12 }}
          volumeMounts:
            - name: sentry-data
              mountPath: /deshchain/.deshchaind
            - name: genesis-config
              mountPath: /genesis
          securityContext:
            runAsUser: 0
            runAsGroup: 0
      containers:
        - name: sentry
          image: "{{ include "deshchain-testnet.imageRegistry" . }}/{{ include "deshchain-testnet.imageRepository" . }}:{{ include "deshchain-testnet.imageTag" . }}"
          imagePullPolicy: {{ include "deshchain-testnet.imagePullPolicy" . }}
          command:
            - deshchaind
            - start
            - --home
            - /deshchain/.deshchaind
            - --log_level
            - info
            - --p2p.laddr
            - tcp://0.0.0.0:26656
            - --rpc.laddr
            - tcp://0.0.0.0:26657
            - --api.enable
            - "true"
            - --api.enabled-unsafe-cors
            - "true"
            - --api.address
            - tcp://0.0.0.0:1317
            - --grpc.enable
            - "true"
            - --grpc.address
            - 0.0.0.0:9090
            - --grpc-web.enable
            - "true"
            - --grpc-web.address
            - 0.0.0.0:9091
            - --pruning
            - custom
            - --pruning-keep-recent
            - "10000"
            - --pruning-keep-every
            - "0"
            - --pruning-interval
            - "10"
            - --minimum-gas-prices
            - 0.01namo
            - --p2p.seeds
            - ""
            - --p2p.persistent_peers
            - {{ include "deshchain-testnet.persistentPeers" . | quote }}
            - --p2p.pex
            - "true"
            - --p2p.allow_duplicate_ip
            - "true"
          ports:
            - name: p2p
              containerPort: 26656
              protocol: TCP
            - name: rpc
              containerPort: 26657
              protocol: TCP
            - name: api
              containerPort: 1317
              protocol: TCP
            - name: grpc
              containerPort: 9090
              protocol: TCP
            - name: grpc-web
              containerPort: 9091
              protocol: TCP
            - name: prometheus
              containerPort: 26660
              protocol: TCP
          env:
            {{- include "deshchain-testnet.commonEnv" . | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /health
              port: 26657
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /status
              port: 26657
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          resources:
            {{- toYaml .Values.sentries.resources | nindent 12 }}
          volumeMounts:
            - name: sentry-data
              mountPath: /deshchain/.deshchaind
            - name: node-config
              mountPath: /deshchain/.deshchaind/config/config.toml
              subPath: sentry-config.toml
              readOnly: true
            - name: node-config
              mountPath: /deshchain/.deshchaind/config/app.toml
              subPath: sentry-app.toml
              readOnly: true
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            capabilities:
              drop:
                - ALL
      {{- with .Values.sentries.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.sentries.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.sentries.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: genesis-config
          configMap:
            name: {{ include "deshchain-testnet.genesisConfigName" . }}
        - name: node-config
          configMap:
            name: {{ include "deshchain-testnet.nodeConfigName" . }}
        {{- if .Values.sentries.persistence.enabled }}
        - name: sentry-data
          persistentVolumeClaim:
            claimName: {{ include "deshchain-testnet.fullname" . }}-sentry-data
        {{- else }}
        - name: sentry-data
          emptyDir: {}
        {{- end }}
{{- end }}