name: batua
description: DeshChain Native Wallet - Your Digital Wallet with Indian Soul
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # State Management
  flutter_riverpod: ^2.4.0
  riverpod_annotation: ^2.2.0
  
  # Navigation & Routing
  go_router: ^12.0.0
  
  # UI Components
  flutter_animate: ^4.2.0
  lottie: ^2.6.0
  shimmer: ^3.0.0
  carousel_slider: ^4.2.1
  smooth_page_indicator: ^1.1.0
  
  # Crypto & Blockchain
  web3dart: ^2.7.1
  bip39: ^1.0.6
  bip32: ^2.0.0
  ed25519_hd_key: ^2.2.0
  pointycastle: ^3.7.3
  crypto: ^3.0.3
  
  # Security
  flutter_secure_storage: ^9.0.0
  local_auth: ^2.1.6
  flutter_screen_lock: ^9.0.0
  
  # Networking
  dio: ^5.3.2
  dio_cache_interceptor: ^3.4.2
  connectivity_plus: ^5.0.0
  
  # Database
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  sqflite: ^2.3.0
  
  # QR Code
  qr_flutter: ^4.1.0
  mobile_scanner: ^3.4.1
  
  # Utilities
  intl: ^0.18.1
  path_provider: ^2.1.1
  share_plus: ^7.2.1
  url_launcher: ^6.1.14
  package_info_plus: ^4.2.0
  device_info_plus: ^9.1.0
  
  # UI Enhancements
  flutter_svg: ^2.0.7
  cached_network_image: ^3.3.0
  google_fonts: ^6.1.0
  flutter_native_splash: ^2.3.2
  
  # Permissions
  permission_handler: ^11.0.0
  
  # Audio
  audioplayers: ^5.2.0
  
  # Notifications
  flutter_local_notifications: ^16.1.0
  firebase_messaging: ^14.7.3
  
  # Analytics & Crash Reporting
  firebase_core: ^2.20.0
  firebase_analytics: ^10.7.1
  firebase_crashlytics: ^3.4.3
  
  # Cultural Features
  flutter_local_notifications_timezone: ^1.0.0
  timezone: ^0.9.2
  
  # JSON
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.6
  riverpod_generator: ^2.3.3
  json_serializable: ^6.7.1
  freezed: ^2.4.5
  hive_generator: ^2.0.1
  flutter_launcher_icons: ^0.13.1
  
flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/images/logo/
    - assets/images/avatars/
    - assets/images/festivals/
    - assets/fonts/
    - assets/sounds/
    - assets/animations/
    - assets/cultural/quotes.json
    - assets/cultural/festivals.json
    - assets/cultural/muhurat.json
  
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
          
    - family: NotoSansDevanagari
      fonts:
        - asset: assets/fonts/NotoSansDevanagari-Regular.ttf
        - asset: assets/fonts/NotoSansDevanagari-Bold.ttf
          weight: 700
          
    - family: Samarkan
      fonts:
        - asset: assets/fonts/Samarkan.ttf

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo/batua_icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/logo/batua_adaptive.png"

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/logo/batua_splash.png
  android_12:
    image: assets/images/logo/batua_splash_android12.png
    icon_background_color: "#FFFFFF"