package types

// Event types
const (
	EventTypeValidatorStaked           = "validator_staked"
	EventTypeTokensVested              = "tokens_vested"
	EventTypeTokensWithdrawn           = "tokens_withdrawn"
	EventTypePerformanceBondReleased   = "performance_bond_released"
	EventTypeValidatorSlashed          = "validator_slashed"
	EventTypeInsuranceClaimFiled       = "insurance_claim_filed"
	EventTypeInsuranceClaimApproved    = "insurance_claim_approved"
	EventTypeValidatorReward           = "validator_reward"
	EventTypeNFTMinted                 = "nft_minted"
	EventTypeNFTTransferred            = "nft_transferred"
	EventTypeValidatorRightsTransferred = "validator_rights_transferred"
	
	// Referral system events
	EventTypeReferralCreated           = "referral_created"
	EventTypeReferralActivated         = "referral_activated"
	EventTypeReferralCommissionPaid    = "referral_commission_paid"
	EventTypeValidatorTokenLaunched    = "validator_token_launched"
	EventTypeTokensAirdropped          = "tokens_airdropped"
	EventTypeCommissionConvertedToLiquidity = "commission_converted_to_liquidity"
	EventTypePlatformFeeCollected      = "platform_fee_collected"
	EventTypeSikkebaazTokenCreated     = "sikkebaaz_token_created"
	EventTypeSikkebaazPoolCreated      = "sikkebaaz_pool_created"
	EventTypeSikkebaazAntiDumpConfigured = "sikkebaaz_anti_dump_configured"
	EventTypeSikkebaazTokensDistributed = "sikkebaaz_tokens_distributed"
	EventTypeSikkebaazTradingEnabled   = "sikkebaaz_trading_enabled"
	EventTypeReferralLiquidityAdded    = "referral_liquidity_added"
	EventTypeReferralCommissionClawedBack = "referral_commission_clawed_back"
)

// Attribute keys
const (
	AttributeKeyValidator          = "validator"
	AttributeKeyRank               = "rank"
	AttributeKeyStakeAmount        = "stake_amount"
	AttributeKeyUSDValue           = "usd_value"
	AttributeKeyNAMOPrice          = "namo_price"
	AttributeKeyTier               = "tier"
	AttributeKeyUnlockedAmount     = "unlocked_amount"
	AttributeKeyTotalUnlocked      = "total_unlocked"
	AttributeKeyAmount             = "amount"
	AttributeKeyRemainingStake     = "remaining_stake"
	AttributeKeySlashingReason     = "slashing_reason"
	AttributeKeySlashingRate       = "slashing_rate"
	AttributeKeyClaimID            = "claim_id"
	AttributeKeyClaimAmount        = "claim_amount"
	AttributeKeyDistributionType   = "distribution_type"
	AttributeKeyTokenID            = "token_id"
	AttributeKeyNFTName            = "nft_name"
	AttributeKeyFrom               = "from"
	AttributeKeyTo                 = "to"
	AttributeKeyPrice              = "price"
	AttributeKeyRoyalty            = "royalty"
	
	// Referral system attribute keys
	AttributeKeyReferralID         = "referral_id"
	AttributeKeyReferrer           = "referrer"
	AttributeKeyReferred           = "referred"
	AttributeKeyCommissionRate     = "commission_rate"
	AttributeKeyTokenName          = "token_name"
	AttributeKeyTokenSymbol        = "token_symbol"
	AttributeKeyTrigger            = "trigger"
	AttributeKeyRecipient          = "recipient"
	AttributeKeyPurpose            = "purpose"
	AttributeKeyVesting            = "vesting"
	AttributeKeyPair               = "pair"
	AttributeKeyPool               = "pool"
	AttributeKeyPoolID             = "pool_id"
	AttributeKeyInitialPrice       = "initial_price"
	AttributeKeyMaxWallet          = "max_wallet"
	AttributeKeyMaxTx              = "max_tx"
	AttributeKeySellTax            = "sell_tax"
	AttributeKeyFeeAmount          = "fee_amount"
	AttributeKeyFeeRecipient       = "fee_recipient"
	AttributeKeyFeePercentage      = "fee_percentage"
	AttributeKeyNAMOAmount         = "namo_amount"
	AttributeKeyTokenAmount        = "token_amount"
	AttributeKeyNetLiquidity       = "net_liquidity"
	AttributeKeyPlatformFee        = "platform_fee"
	AttributeKeyLiquidityLocked    = "liquidity_locked"
	AttributeKeyClawbackAmount     = "clawback_amount"
	AttributeKeyClawbackReason     = "clawback_reason"
)